---

- name: Install zsh in Redhat derivatives
  sudo: yes
  yum: name=zsh state=installed
  when: ansible_os_family == 'RedHat'

- name: Install zsh in Debian derivatives
  sudo: yes
  apt: pkg=zsh state=present
  when: ansible_os_family == 'Debian'

- name: install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  sudo: false

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~{{user}}/.zshrc ]; then mv -f ~{{user}}/.zshrc ~{{user}}/.zshrc.orig ; fi
  sudo: false

- name: Backing up existing ~/.env.sh
  shell: if [ -f ~{{user}}/.env.sh ]; then mv -f ~{{user}}/.env.sh ~{{user}}/.env.sh.orig ; fi
  sudo: false

- copy: src=./files/.zshrc dest=~{{user}}/.zshrc

- copy: src=./files/.env.sh dest=~{{user}}/.env.sh

- name: switch to ZSH
  user: name={{user}} shell=/usr/bin/zsh
  sudo: True
